CREATE TABLE IF NOT EXISTS core.forbidden_keywords (
    id           uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    keyword      text        NOT NULL,
    category     text        NOT NULL DEFAULT 'politics',
    enabled      boolean     NOT NULL DEFAULT true,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    UNIQUE (keyword)
);

CREATE INDEX IF NOT EXISTS ix_forbidden_keywords_enabled
    ON core.forbidden_keywords (enabled, category);

-- noop on fresh init; backfill applied via bootstrap
INSERT INTO core.forbidden_keywords (keyword, category) VALUES
    ('арест', 'crime'),
    ('взятк', 'crime'),
    ('взять в плен', 'crime'),
    ('задержан', 'crime'),
    ('задержание', 'crime'),
    ('заложник', 'crime'),
    ('изнасилов', 'crime'),
    ('казнь', 'crime'),
    ('коррупц', 'crime'),
    ('мвд', 'crime'),
    ('мошенн', 'crime'),
    ('наркот', 'crime'),
    ('обыск', 'crime'),
    ('пожизненн', 'crime'),
    ('преступл', 'crime'),
    ('преступник', 'crime'),
    ('прокурор', 'crime'),
    ('расстрел', 'crime'),
    ('сизо', 'crime'),
    ('следственн', 'crime'),
    ('смертная казнь', 'crime'),
    ('стрельб', 'crime'),
    ('тюрьм', 'crime'),
    ('убийств', 'crime'),
    ('уголовн', 'crime'),
    ('фсб', 'crime'),
    ('cia', 'politics'),
    ('javelin', 'politics'),
    ('mi6', 'politics'),
    ('абрамс', 'politics'),
    ('авдеевк', 'politics'),
    ('агресс', 'politics'),
    ('азербайджан', 'politics'),
    ('армени', 'politics'),
    ('артиллер', 'politics'),
    ('асад', 'politics'),
    ('атак на', 'politics'),
    ('атомн', 'politics'),
    ('афган', 'politics'),
    ('байден', 'politics'),
    ('баллистическ', 'politics'),
    ('бахмут', 'politics'),
    ('беларус', 'politics'),
    ('белгород', 'politics'),
    ('беспилотник', 'politics'),
    ('блиндаж', 'politics'),
    ('боевик', 'politics'),
    ('боевые действия', 'politics'),
    ('боевых действий', 'politics'),
    ('боеприпас', 'politics'),
    ('бомб', 'politics'),
    ('бпла', 'politics'),
    ('брюссел', 'politics'),
    ('брянск', 'politics'),
    ('вагнер', 'politics'),
    ('вашингтон', 'politics'),
    ('взрыв', 'politics'),
    ('взрывн', 'politics'),
    ('взрывчатк', 'politics'),
    ('военкомат', 'politics'),
    ('военн', 'politics'),
    ('война', 'politics'),
    ('воронеж', 'politics'),
    ('всу', 'politics'),
    ('гаубиц', 'politics'),
    ('геноцид', 'politics'),
    ('генштаб', 'politics'),
    ('герань', 'politics'),
    ('герасимов', 'politics'),
    ('госдеп', 'politics'),
    ('госдума', 'politics'),
    ('госпереворот', 'politics'),
    ('гру', 'politics'),
    ('грузи', 'politics'),
    ('дезерт', 'politics'),
    ('депутат', 'politics'),
    ('деэскалац', 'politics'),
    ('джихад', 'politics'),
    ('диверс', 'politics'),
    ('диктатор', 'politics'),
    ('днепр', 'politics'),
    ('днр', 'politics'),
    ('донецк', 'politics'),
    ('дрон', 'politics'),
    ('евросоюз', 'politics'),
    ('ермак', 'politics'),
    ('заминирован', 'politics'),
    ('запорож', 'politics'),
    ('зеленск', 'politics'),
    ('зеленский', 'politics'),
    ('зеленского', 'politics'),
    ('зурабов', 'politics'),
    ('игил', 'politics'),
    ('израил', 'politics'),
    ('изюм', 'politics'),
    ('импичмент', 'politics'),
    ('иноаген', 'politics'),
    ('ирак', 'politics'),
    ('иран', 'politics'),
    ('искандер', 'politics'),
    ('исламск', 'politics'),
    ('йемен', 'politics'),
    ('кадыров', 'politics'),
    ('казахст', 'politics'),
    ('калибр', 'politics'),
    ('капитуляц', 'politics'),
    ('киев', 'politics'),
    ('киевск', 'politics'),
    ('кинжал', 'politics'),
    ('киргиз', 'politics'),
    ('кндр', 'politics'),
    ('конфликт', 'politics'),
    ('краматорск', 'politics'),
    ('кремл', 'politics'),
    ('крым', 'politics'),
    ('купянск', 'politics'),
    ('курск', 'politics'),
    ('лавров', 'politics'),
    ('ланцет', 'politics'),
    ('лгбт', 'politics'),
    ('леопард', 'politics'),
    ('ливан', 'politics'),
    ('ликвидирован', 'politics'),
    ('линия фронта', 'politics'),
    ('лнр', 'politics'),
    ('луганск', 'politics'),
    ('лукашенк', 'politics'),
    ('львов', 'politics'),
    ('мариуполь', 'politics'),
    ('массакр', 'politics'),
    ('массированн', 'politics'),
    ('минобороны', 'politics'),
    ('митинг', 'politics'),
    ('мобилизац', 'politics'),
    ('молдов', 'politics'),
    ('моссад', 'politics'),
    ('навальн', 'politics'),
    ('наемник', 'politics'),
    ('наступлен', 'politics'),
    ('нато', 'politics'),
    ('наёмник', 'politics'),
    ('нетаньяху', 'politics'),
    ('николаев', 'politics'),
    ('обстрел', 'politics'),
    ('одесса', 'politics'),
    ('окоп', 'politics'),
    ('окруж', 'politics'),
    ('оон', 'politics'),
    ('оппозиц', 'politics'),
    ('оружие', 'politics'),
    ('палестин', 'politics'),
    ('партизан', 'politics'),
    ('пво', 'politics'),
    ('пентагон', 'politics'),
    ('переворот', 'politics'),
    ('переговор', 'politics'),
    ('передовая', 'politics'),
    ('перемири', 'politics'),
    ('песков', 'politics'),
    ('пленн', 'politics'),
    ('повестк', 'politics'),
    ('погиб', 'politics'),
    ('подбит', 'politics'),
    ('политз', 'politics'),
    ('политическ', 'politics'),
    ('пригожин', 'politics'),
    ('призыв', 'politics'),
    ('протест', 'politics'),
    ('путин', 'politics'),
    ('путина', 'politics'),
    ('путину', 'politics'),
    ('путч', 'politics'),
    ('пытк', 'politics'),
    ('пэтриот', 'politics'),
    ('радикал', 'politics'),
    ('ракет', 'politics'),
    ('ракетн', 'politics'),
    ('ранен', 'politics'),
    ('раненн', 'politics'),
    ('революци', 'politics'),
    ('режим контртеррористическ', 'politics'),
    ('россий', 'politics'),
    ('российск', 'politics'),
    ('рязань', 'politics'),
    ('санкци', 'politics'),
    ('сбу', 'politics'),
    ('сво', 'politics'),
    ('сдача в плен', 'politics'),
    ('севастополь', 'politics'),
    ('северная коре', 'politics'),
    ('сектор газа', 'politics'),
    ('сепаратист', 'politics'),
    ('симферополь', 'politics'),
    ('сирия', 'politics'),
    ('сиси', 'politics'),
    ('славянск', 'politics'),
    ('снаряд', 'politics'),
    ('спецоперац', 'politics'),
    ('таджик', 'politics'),
    ('талибан', 'politics'),
    ('танк', 'politics'),
    ('теракт', 'politics'),
    ('терактах', 'politics'),
    ('терактов', 'politics'),
    ('терактом', 'politics'),
    ('терроризм', 'politics'),
    ('трамп', 'politics'),
    ('убит', 'politics'),
    ('удар по', 'politics'),
    ('узбекист', 'politics'),
    ('украин', 'politics'),
    ('украинск', 'politics'),
    ('уничтожен', 'politics'),
    ('хаймарс', 'politics'),
    ('хамас', 'politics'),
    ('харьков', 'politics'),
    ('хезболл', 'politics'),
    ('херсон', 'politics'),
    ('хунт', 'politics'),
    ('хуситы', 'politics'),
    ('чвк', 'politics'),
    ('шахед', 'politics'),
    ('шахид', 'politics'),
    ('шойгу', 'politics'),
    ('штурм', 'politics'),
    ('экстремист', 'politics'),
    ('экстремистск', 'politics'),
    ('эрдоган', 'politics'),
    ('эскалац', 'politics'),
    ('ядерн', 'politics')
ON CONFLICT (keyword) DO NOTHING;
